# item-service-dev.yml
server:
  port: 8001
  
  
spring:
  application:
    name: item-service
  cloud:
    config:
      override-none: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
management:
  endpoints:
    web:
      exposure:
        include: refresh